#!/usr/bin/env bash

# sf -- script framework (https://github.com/Deleh/sf)

# Text formatting variables
sftrs=$'\e[0m'
sftbf=$'\e[1m'
sftdim=$'\e[2m'
sftul=$'\e[4m'
sftblk=$'\e[5m'
sftinv=$'\e[7m'
sfthdn=$'\e[8m'
sftclr=$'\e[1A\e[K'
sftk=$'\e[30m'
sftr=$'\e[31m'
sftg=$'\e[32m'
sfty=$'\e[33m'
sftb=$'\e[34m'
sftm=$'\e[35m'
sftc=$'\e[36m'
sftw=$'\e[97m'

# Public output functions
function sferr {
    echo -e "${sftbf}${sftr}ERROR${sftrs} $1"
    [ -z "$2" ] && exit 1
}

function sfwarn {
    echo -e "${sftbf}${sfty}WARNING${sftrs} $1"
}

# Public input functions
function sfask {
    if [ -n "$2" ]; then
        echo -ne "$1? [${sftbf}y${sftrs}/${sftbf}N${sftrs}] "
        read -r sfin
        [[ "$sfin" =~ n|N|^$ ]] && sfin=false || sfin=true
    else
        echo -ne "$1? [${sftbf}Y${sftrs}/${sftbf}n${sftrs}] "
        read -r sfin
        [[ "$sfin" =~ y|Y|^$ ]] && sfin=true || sfin=false
    fi
}

function sfget {
    if [ -n "$2" ]; then
        read -r -p "$1 [${sftbf}$2${sftrs}]: " sfin
    else
        read -r -p "$1: " sfin
    fi
    [ "$sfin" == "" ] && [ "$2" != "" ] && sfin="$2"
}

# Internal error function
function _sferr {
    echo "${sftbf}${sftr}SF PARSE ERROR${sftrs} $1"
    exit 1
}

# Declare variables for parsing
OLDIFS=$IFS
IFS=";"
_sfpargs=()
_sfpheads=()
_sfpoffset=0
_sfptails=()
_sfpusage=""
_sfoheads=()
_sfooffset=0
_sfotails=()
declare -A _sfflags
declare -A _sfargs

# Parse sf arguments
sfargs=("${sfargs[@]}" "help;h;Show this help message and exit")
for a in "${sfargs[@]}"; do

    # Get amount of semicolons
    _sfsubst=${a//";"}
    _sfcount="$(( ${#a} - ${#_sfsubst} ))"

    # Positional arguments
    if [ "$_sfcount" -eq 1 ]; then

        # Read positional argument declaration
        read -r -a _sfparsearr <<< "${a}"

        # Add to positional argument arry
        [[ " ${_sfpargs[*]} " =~ " ${_sfparsearr[0]} " ]] && _sferr "${sftbf}${_sfparsearr[0]}${sftrs} is already set: ${sftbf}${a}${sftrs}"
        _sfpargs+=("${_sfparsearr[0]}")

        # Set usage header and append description arrays
        _sfpusage="$_sfpusage ${_sfparsearr[0]}"
        _sfphead="${_sfparsearr[0]}"
        [ "${#_sfphead}" -gt "${_sfpoffset}" ] && _sfpoffset="${#_sfphead}"
        _sfpheads+=("$_sfphead")
        _sfptails+=("${_sfparsearr[1]}")

    # Flags
    elif [ "$_sfcount" -eq 2 ]; then

        # Read flag declaration
        read -r -a _sfparsearr <<< "${a}"

        # Set mappings
        [ -n "${_sfflags["--${_sfparsearr[0]}"]}" ] && _sferr "${sftbf}${_sfparsearr[0]}${sftrs} is already set: ${sftbf}${a}${sftrs}"
        _sfflags["--${_sfparsearr[0]}"]="${_sfparsearr[0]}"
        [ -n "${_sfflags["-${_sfparsearr[1]}"]}" ] && _sferr "${sftbf}${_sfparsearr[1]}${sftrs} is already set: ${sftbf}${a}${sftrs}"
        _sfflags["-${_sfparsearr[1]}"]="${_sfparsearr[0]}"

        # Set default value
        declare "${_sfparsearr[0]//-/_}"=false

        # Append description arrays
        _sfohead="-${_sfparsearr[1]}, --${_sfparsearr[0]}"
        [ "${#_sfohead}" -gt "${_sfooffset}" ] && _sfooffset="${#_sfohead}"
        _sfoheads+=("$_sfohead")
        _sfotails+=("${_sfparsearr[2]}")

    # Arguments
    elif [ "$_sfcount" -eq 4 ]; then

        # Read argument declaration
        read -r -a _sfparsearr <<< "${a}"

        # Set mappings
        [ -n "${_sfargs["--${_sfparsearr[0]}"]}" ] && _sferr "${sftbf}${_sfparsearr[0]}${sftrs} is already set: ${sftbf}${a}${sftrs}"
        _sfargs["--${_sfparsearr[0]}"]="${_sfparsearr[0]}"
        [ -n "${_sfargs["-${_sfparsearr[1]}"]}" ] && _sferr "${sftbf}${_sfparsearr[1]}${sftrs} is already set: ${sftbf}${a}${sftrs}"
        _sfargs["-${_sfparsearr[1]}"]="${_sfparsearr[0]}"

        # Set default value
        declare "${_sfparsearr[0]//-/_}"="${_sfparsearr[3]}"

        # Append description arrays
        _sfohead="-${_sfparsearr[1]}, --${_sfparsearr[0]} ${_sfparsearr[2]}"
        [ "${#_sfohead}" -gt "${_sfooffset}" ] && _sfooffset="${#_sfohead}"
        _sfoheads+=("$_sfohead")
        [ "${_sfparsearr[3]}" != "" ] && _sfotails+=("${_sfparsearr[4]} (default: ${_sfparsearr[3]})") || _sfotails+=("${_sfparsearr[4]}")

    else
        _sferr "Wrong argument declaration: ${sftbf}${a}${sftrs}"
    fi
done

# Parse examples
_sfeheads=()
_sfetails=()
_sfeoffset=0
for e in "${sfexamples[@]}"; do

    # Get amount of ;
    _sfsubst=${e//";"}
    _sfcount="$(( ${#e} - ${#_sfsubst} ))"

    if [ "$_sfcount" -eq 1 ]; then

        # Read example
        read -r -a _sfparsearr <<< "${e}"

        # Append example arrays
        _sfehead="${_sfparsearr[0]}"
        [ "${#_sfehead}" -gt "${_sfeoffset}" ] && _sfeoffset="${#_sfehead}"
        _sfeheads+=("$_sfehead")
        _sfetails+=("${_sfparsearr[1]}")

    else
        _sferr "Wrong example declaration: ${sftbf}${e}${sftrs}"
    fi
done

IFS=$OLDIFS

# Check if at least one positional argument is set if 'sfparr' is used
[ "$sfparr" == true ] && [ "${#_sfpargs[@]}" == 0 ] && _sferr "At least one positional argument must be used with ${sftbf}sfparr${sftrs}"

# Correct positional argument description if 'sfparr' is used
[ "$sfparr" == true ] && _sfpusage="${_sfpusage% *} [${_sfpusage##* } ...]"

# Correct offsets
_sfpoffset=$(( "_sfpoffset" + 3 ))
_sfooffset=$(( "_sfooffset" + 3 ))
_sfeoffset=$(( "_sfeoffset" + 3 ))

# Set _sfwidth to current terminal width
_sfwidth=$(stty size | cut -d ' ' -f 2)

# Create positional argument description with correct line breaks
_sfpdesc=""
for i in "${!_sfptails[@]}"; do
    _sfptail="${_sfptails[$i]}"
    if [ "$(( ${#_sfptail} + _sfpoffset ))" -gt "$_sfwidth" ]; then
        _sftmpwidth="$(( _sfwidth - _sfpoffset ))"
        _sftmpwidth=$(echo -e "${_sftmpwidth}\n1" | sort -nr | head -n 1)
        _sfptail=$(echo "$_sfptail" | fold -s -w "$_sftmpwidth")
        _sfptail="${_sfptail//$' \n'/$'\n;'}"
    fi
    _sfpdesc="${_sfpdesc}  ${_sfpheads[$i]};${_sfptail}\n"
done

# Create option description with correct line breaks
_sfodesc=""
for i in "${!_sfotails[@]}"; do
    _sfotail="${_sfotails[$i]}"
    if [ "$(( ${#_sfotail} + _sfooffset ))" -gt "$_sfwidth" ]; then
        _sftmpwidth="$(( _sfwidth - _sfooffset ))"
        _sftmpwidth=$(echo -e "${_sftmpwidth}\n1" | sort -nr | head -n 1)
        _sfotail=$(echo "$_sfotail" | fold -s -w "$_sftmpwidth")
        _sfotail="${_sfotail//$' \n'/$'\n;'}"
    fi
    _sfodesc="${_sfodesc}  ${_sfoheads[$i]};${_sfotail}\n"
done

# Create examples description with correct line breaks
_sfexamples=""
for i in "${!_sfetails[@]}"; do
    _sfetail="${_sfetails[$i]}"
    if [ "$(( ${#_sfetail} + _sfeoffset ))" -gt "$_sfwidth" ]; then
        _sftmpwidth="$(( _sfwidth - _sfeoffset ))"
        _sftmpwidth=$(echo -e "${_sftmpwidth}\n1" | sort -nr | head -n 1)
        _sfetail=$(echo "$_sfetail" | fold -s -w "$_sftmpwidth")
        _sfetail="${_sfetail//$' \n'/$'\n;'}"
    fi
    _sfexamples="${_sfexamples}  ${_sfeheads[$i]};${_sfetail}\n"
done

# Usage function
function _sfusage {
    echo -n "Usage: $(basename "$0") [OPTIONS]"
    echo -ne "$_sfpusage"
    echo
    [ -n "${sfdesc}" ] && echo -e "\n$sfdesc" | fold -s -w "$_sfwidth"
    if [ "$_sfpdesc" != "" ]; then
        echo -e "\nPOSITIONAL ARGUMENTS"
        echo -e "$_sfpdesc" | column -s ";" -t
    fi
    if [ "$_sfodesc" != "" ]; then
        echo -e "\nOPTIONS"
        echo -e "$_sfodesc" | column -s ";" -t
    fi
    if [ "$_sfexamples" != "" ]; then
        echo -e "\nEXAMPLES"
        echo -e "$_sfexamples" | column -s ";" -t
    fi
    if [ -n "${sfextra}" ]; then
        echo -e "\n$sfextra"
    fi
    exit 0
}

# Check for help flag
for a in "$@"; do
    # Check if help flag ist set
    [ "$a" == "-h" ] || [ "$a" == "--help" ] && _sfusage
done

# Check if dependencies are available
for d in "${sfdeps[@]}"; do
    if ! command -v "$d" &> /dev/null; then
        sferr "Command ${sftbf}${d}${sftrs} not found" 0
        _sfdeperr=true
    fi
done
[ "$_sfdeperr" == true ] && exit 1

# Parse arguments
while (( "$#" )); do

    # Check if flag
    if [ -n "${_sfflags["$1"]}" ]; then
        declare "${_sfflags["$1"]//-/_}"=true

    # Check if argument
    elif [ -n "${_sfargs["$1"]}" ]; then

        # Check if argument has value
        if [ -n "$2" ] && [ "${2:0:1}" != "-" ]; then
            declare "${_sfargs["$1"]//-/_}"="$2"
            shift
        else
            sferr "Argument for ${sftbf}${1}${sftrs} missing"
        fi

    # Handle positional arguments and wrong arguments/flags
    else
        # Check if arg starts with -
        if [ "${1:0:1}" == "-" ]; then
            sferr "Unsupported argument/flag ${sftbf}${1}${sftrs}"
        else
            # Set positional argument
            if [ "${#_sfpargs[@]}" != 0 ]; then
                declare "${_sfpargs[0]//-/_}"="$1"
                [ "$sfparr" == true ] && _sfplast="${_sfpargs[0]//-/_}" && _sfparr=("$1")
                _sfpargs=("${_sfpargs[@]:1}")
            elif [ "$sfparr" == true ]; then
                _sfparr+=("$1")
            else
                sferr "Too many positional arguments"
            fi
        fi
    fi
    shift
done

# Parse additional arguments if 'sfparr' is set
[ "$sfparr" == true ] && [ "${#_sfparr[@]}" -gt 0 ] && read -r -a "${_sfplast?}" <<< "${_sfparr[@]}"

# Remove last missing argument to allow empty arrays if 'sfparr' is set
[ "$sfparr" == true ] && [ "${#_sfpargs[@]}" -gt 0 ] && unset '_sfpargs[${#_sfpargs[@]}-1]'

# Check if positional arguments left
if [ "${#_sfpargs[@]}" -gt 0 ]; then
    for p in "${_sfpargs[@]}"; do
        sferr "Positional argument ${sftbf}${p}${sftrs} missing" 0
    done
    exit 1
fi

# Unset all internal variables and functions
unset a d e i OLDIFS _sfargs _sfehead _sfeheads _sfeoffset _sferr _sfetails _sfexamples _sfflags _sfodesc _sfohead _sfoheads _sfooffset _sfotails _sfpargs _sfparr _sfpdesc _sfphead _sfpheads _sfplast _sfpoffset _sfptails _sfpusage _sftmpwidth _sfusage _sfwidth
