#!/usr/bin/env bash

# ----------------------
# sf -- script framework
# ----------------------

# Declare sf variables
sfdesc="A script that shows the usage of 'sfdeps'. It should always throw an error."

sfdeps=("source" "nonexistent" "alsononexistent" "echo")

# Include sf, this could be replaced with a long oneliner
source "$(dirname $0)/../sf"

# ----------------------
# Actual script
# ----------------------

echo "If you see this, the commands 'source', 'nonexistent', 'alsononexistent' and 'echo' are available."
